services:
  redis: 
    image: redis:7.4.1-alpine
    container_name: spimex_cache
    restart: always
    environment:
      - REDIS_CONFIG__PASSWORD=${REDIS_CONFIG__PASSWORD}
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "${REDIS_CONFIG__PASSWORD}"]
    networks:
      - spimex_local
    ports:
      - "6379:6379"

networks:
  spimex_local:
    driver: bridge

volumes:
  redis-data: 
